version: '3'

networks:
  kvcore-network:
    driver: bridge
    ipam:
      driver: default

services:
    kvcore-nginx:
        container_name: kvcore-nginx
        image: nginx
        ports:
            - '8090:80'
        links:
            - kvcore-api
        volumes:
            - ../src:/var/www
            - ./nginx/app.conf:/etc/nginx/conf.d/default.conf    
        networks:
            - kvcore-network

    kvcore-api:
        container_name: kvcore-api
        build:
            context: .
            dockerfile: api.Dockerfile
        image: kvcore-api
        ports:
            - '9000:9000'
        volumes:
            - ../../kunversion-api:/var/www
            - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - kvcore-network

    kvcore-db:
        container_name: kvcore-db
        image: mysql:8.0
        ports:
            - '3030:3306'
        volumes:
            - ./mysql/my.cnf:/etc/mysql/my.cnf
            - ./mysql/init:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=secret
        networks:
            - kvcore-network

    kvcore-db-test:
        container_name: kvcore-db-test
        image: mysql:8.0
        ports:
            - '3031:3306'
        volumes:
            - ./mysql/my.cnf:/etc/mysql/my.cnf
            - ./mysql/init-test:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=secret
        networks:
            - kvcore-network